version: '3'
services:
  # Service pour la base de données MySQL
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: database_development
      MYSQL_USER: root
      MYSQL_PASSWORD: toor
    ports:
      - "3306:3306"

  # Service pour le backend Node.js
  backend:
    image: alphonsine/backend:latest
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: toor
      DB_NAME: database_development

  # Service pour le frontend
  frontend:
    image: alphonsine/frontend:latest
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend